ERROR    my_log:test_login.py:24 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-08 21:28:48', 'sessionId': 'ffe562ff90fb646db11965c58ea3b8c7', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwNDQ1MzI4MTI3fQ.T64imkE6fBv2zGozSj9fsVe6w6Jhx_JwcX9s0i0NZyyttejOqEVQ7kGAp9CRYEQXRazk6l8VsOkb0dO1kVgMo_JjJsTdKiLfNjt7OFvA0-D1WOtlhdwgU5KoH3Eqw0_NoVhNnwBdEa_A0DjXNC1Hc33mN3bI4ETSWn7XKabkPsA'}}"}