ERROR    my_log:test_login.py:24 接口{"{'code': 'SUCCESS', 'message': '操作成功', 'traceId': '', 'data': {'user': {'id': 1389, 'employeeId': None, 'nickname': '随机昵称', 'avatar': 'https://msb-edu-prod.oss-cn-beijing.aliyuncs.com/default-headimg.png', 'phone': '16688888888', 'systemId': 0, 'clientId': 0, 'unionId': '', 'tokenExpireTime': '2025-07-14 16:58:17', 'sessionId': '03911aea5d96d83cdbe5c7a091ea43ae', 'token': None}, 'token': 'eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjQwNzA4ODAwMDAsImlkIjoxMzg5LCJ0aW1lIjoxNzIwOTQ3NDk3MTk2fQ.pYdGLkh9aO31_VN-kiSeT8W5hvUgAFaNnfoTjYf9QD-9pFp9juRSR_t3J4IKtyCgbe7edopqTXSptCkJ05VzOd70FYdbHFNYsiDNhgxYsUKtTcvWX9K-h5WponHul8TmDz3DSKpcxhQrabn9afwRNN54t_6Ec5fWf1tGqW1saw4'}}"}